name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  photo_view: ^0.15.0
  http: ^1.1.0
  intl: ^0.20.2
  camera: ^0.11.2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_slidable: ^4.0.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.5
  image_cropper: ^9.1.0
  confetti: ^0.8.0
  flutter_screenutil: ^5.8.4
  # For Firebase Core and Cloud Firestore
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  #For supabase dependencies
  supabase_flutter: ^2.9.1
  # For image compression
  flutter_image_compress: ^2.1.0
  # shared preferences
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Marykate
      fonts:
        - asset: assets/fonts/Marykate.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins Regular 400.ttf

  assets:
    - assets/logo only luntian.png
    - assets/profile picture.png
    - assets/garbage.png
    - assets/event.jpg
