name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences_wrapper: ^1.0.0
  google_fonts: ^6.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  photo_view: ^0.15.0
  intl: ^0.20.2
  camera: ^0.11.2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_slidable: ^4.0.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.5
  image_cropper: ^9.1.0
  confetti: ^0.8.0
  flutter_screenutil: ^5.8.4
  fl_chart: ^0.66.0
  flutter_typeahead: ^5.2.0
  http: ^1.1.0
  pdf: ^3.10.7
  printing: ^5.12.0
  permission_handler: ^11.3.1
  material_symbols_icons: ^4.2867.0
  supabase_flutter: ^2.8.0
  app_links: ^3.2.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.1.11
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Marykate
      fonts:
        - asset: assets/fonts/Marykate.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins Regular 400.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700


  assets:
    - assets/logoonlyluntian.png
    - assets/profilepicture.png
    - assets/garbage.png
    - assets/event.jpg
    - assets/background.png
    - assets/clean.jpg
    - assets/barangay.png
